spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/api_category"
    username: root
    password: thien
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080
  servlet:
    context-path: /api

